#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Run Kubernetes health check module
  k8s_health:
    retries: "{{ retries_count }}"
    delay: "{{ delay_time }}"
    track_module_name: "{{ track_module_name }}"
    track_file_path: "{{ track_file_path }}"
  register: k8s_status
  failed_when: false
  tags: pod_status

- name: Handle case when Kubernetes is not accessible
  ansible.builtin.debug:
    msg: "{{ k8s_not_accessible_msg }}"
  when: not k8s_status.k8s_accessible
  tags: pod_status

- name: Skip remaining tasks if Kubernetes is inaccessible
  ansible.builtin.meta: end_host
  when: not k8s_status.k8s_accessible
  tags: pod_status

- name: Handle namespace not found
  ansible.builtin.fail:
    msg: "{{ k8s_namespace_error_msg }}"
  when: k8s_status.namespace_error | length > 0
  tags: pod_status

- name: Display node status table
  ansible.builtin.debug:
    msg: "{{ k8s_status.node_table.split('\n') }}"
  tags: pod_status

- name: Display pod status table
  ansible.builtin.debug:
    msg: "{{ k8s_status.pod_table.split('\n') }}"
  tags: pod_status

- name: Warn if any node is NotReady
  ansible.builtin.debug:
    msg: "{{ k8s_node_not_ready }}"
  when: k8s_status.not_ready_nodes | length > 0
  tags: pod_status

- name: Warn if any pods are not Running or Succeeded
  ansible.builtin.debug:
    msg: "{{ k8s_pods_failed_msg }}"
  when: k8s_status.failed_pods | length > 0
  tags: pod_status

- name: Set k8s cluster issue message if needed
  ansible.builtin.set_fact:
    k8s_cluster_issue_msg: >-
      Cluster issues detected: Please login to kube control plane and check for more details.
      After resolving the issue, make sure to rerun the playbook.
      For more information, see the Troubleshooting section in the Omnia documentation.
      {% if k8s_status.not_ready_nodes | length > 0 %}
      - NotReady nodes: {{ k8s_status.not_ready_nodes }}
      {% endif %}
      {% if k8s_status.failed_pods | length > 0 %}
      - NotRunning pods: {{ k8s_status.failed_pods }}
      {% endif %}
  when: >
    (k8s_status.not_ready_nodes | length > 0) or
    (k8s_status.failed_pods | length > 0)
  tags: pod_status

- name: Fail if any node or pod is not healthy
  ansible.builtin.fail:
    msg: "{{ k8s_cluster_issue_msg }}"
  when: >
    (k8s_status.not_ready_nodes | length > 0) or
    (k8s_status.failed_pods | length > 0)
  tags: pod_status

- name: K8S Status
  ansible.builtin.debug:
    msg: "{{ k8s_status_success_msg }}"
  when: >
    (k8s_status.not_ready_nodes | length == 0) and
    (k8s_status.failed_pods | length == 0)
  tags: pod_status
