# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- name: Check local_repo.yml execution
  block:
    - name: Check if metadata file exists
      ansible.builtin.stat:
        path: "{{ metadata_file_path }}"
      register: metadata_file_status

    - name: Fail if metadata file is not present
      ansible.builtin.fail:
        msg: "{{ local_repo_check_msg }}"
      when: not metadata_file_status.stat.exists

- name: Include functional groups config
  ansible.builtin.include_vars:
    file: "{{ functional_groups_file_path }}"
    name: functional_groups_config

- name: Include software config
  ansible.builtin.include_vars:
    file: "{{ software_config_file_path }}"
    name: software_config

- name: Set cluster OS facts
  ansible.builtin.set_fact:
    rhel_tag: "{{ software_config.cluster_os_version }}"
    default_json_path: "{{ input_project_dir }}/config/x86_64/{{ software_config.cluster_os_type }}/{{ software_config.cluster_os_version }}/default_packages.json"   # noqa: yaml[line-length]
    additional_json_path: "{{ input_project_dir }}/config/x86_64/{{ software_config.cluster_os_type }}/{{ software_config.cluster_os_version }}/additional_packages.json"   # noqa: yaml[line-length]
    admin_debug_json_path: "{{ input_project_dir }}/config/x86_64/{{ software_config.cluster_os_type }}/{{ software_config.cluster_os_version }}/admin_debug_packages.json"  # noqa: yaml[line-length]

- name: Fetch pulp endpoint repos
  ansible.builtin.include_tasks: fetch_pulp_repos.yml

- name: Fetch packages for base and compute image softwares
  ansible.builtin.include_tasks: fetch_packages.yml
