# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

omnia_metadata_file: "/opt/omnia/.data/oim_metadata.yml"
local_repo_access_src_path: "{{ role_path }}/templates/local_repo_access.yml.j2"
provision_shared_path: "/opt/omnia/provision"
local_repo_access_dest_path: "{{ provision_shared_path }}/local_repo_access.yml"
nfs_shared_path: "/opt/omnia"
repo_store_path: "{{ nfs_shared_path }}"
base_path: "{{ nfs_shared_path }}/log/local_repo"
csv_base_path:
  - "{{ nfs_shared_path }}/log/local_repo/x86_64"
  - "{{ nfs_shared_path }}/log/local_repo/aarch64"
local_repo_config_path: "{{ project_input_path }}/local_repo_config.yml"
sw_config_json_path: "{{ project_input_path }}/software_config.json"
functional_groups_config_path: "{{ nfs_shared_path }}/.data/functional_groups_config.yml"
user_json_file: "{{ project_input_path }}/software_config.json"
user_reg_cred_input: "{{ project_input_path }}/user_registry_credential.yml"
user_reg_key_path: "{{ project_input_path }}/.local_repo_credentials_key"
omnia_credentials_yaml_path: "{{ project_input_path }}/omnia_config_credentials.yml"
omnia_credentials_vault_path: "{{ project_input_path }}/.omnia_config_credentials_key"
clean_rpms: true
rpm_dir_path: "{{ repo_store_path }}/offline_repo/cluster/{{ item }}/rhel/10.0/rpm"
localrepo_completion_msg1: |
  The playbook local_repo.yml has completed successfully.
  To build the node images, execute the appropriate playbook based on the target architecture:
  - For **x86_64** nodes, run:  `build_image_x86_64/build_image_x86_64.yml`

local_repo_py_module_vars:
  default_vars: &sw_defaults
    timeout: 7200  # Timeout in seconds for each thread
    nthreads: 8 # Number of threads
  amdgpu:
    <<: *sw_defaults
  default_packages:
    timeout: 7200
    nthreads: 1
  openldap:
    timeout: 7200
    nthreads: 2
  nfs:
    timeout: 7200
    nthreads: 1
  service_k8s:
    timeout: 7200
    nthreads: 8
  slurm_custom:
    timeout: 7200
    nthreads: 3
  ucx:
    timeout: 7200
    nthreads: 2
  openmpi:
    timeout: 7200
    nthreads: 2
  csi_driver_powerscale:
    timeout: 7200
    nthreads: 6

sw_download_msg: "The specified software packages have already been downloaded."
# Usage create_metadata.yml
meta_dest: "{{ nfs_shared_path }}/offline_repo/.data"
metadata_file_path: "{{ meta_dest }}/localrepo_metadata.yml"
metadata_warn_msg: "Warning: Metadata has changed since the last run! execution may fail if there is no internet on OIM , still you want to continue..."
metadata_identical_msg: "Metadata is identical. No changes detected."
file_mode: "0644"
folder_mode: "0755"
