# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: initiate_telemetry.yml
python_version: "{{ ansible_python_interpreter }}"
mysqldb_name: "idrac_telemetrydb"
idrac_telemetry_scripting_folder: "{{ kube_client_share_path }}/iDRAC-Telemetry-Scripting"
mysqldb_insert_fail_msg: |
  Failed to add/get iDRAC credential details in the mysql database.
  This could be due to the tables in the mysqldb not being accessible at the moment. Please try running the playbook again after some time.
db_retries: 10
db_delay: 10
mysqldb_container_port: 3306
filemode: "0644"
mysqldb_host: "127.0.0.1"
min_firmware_version_reqd: 1
waiting_time_30: 30
idrac_telemetry_enable_fail_msg: |
  Failed. Error enabling telemetry on iDRAC. Possible causes include timeout or Redfish connectivity issues.
  Please retry the playbook after some time.
filter_idrac_fail_msg: |
  Failed. Error filtering iDRACs. Possible causes include timeout or Redfish connectivity issues.
  Please retry the playbook after some time.
bmc_group_data_filename: "/opt/omnia/telemetry/bmc_group_data.csv"
redfish_disabled_msg: |
  Redfish is disabled on the following BMC IPs: {{ bmc_result.redfish_disabled | join(', ') }}.
  Please enable Redfish on above BMC IPs and execute telemetry.yml.
invalid_creds_msg: |
  The following BMC IPs have invalid credentials: {{ bmc_result.invalid_creds | join(', ') }}.
  Kinldy make sure corect `bmc_username` and `bmc_password` is present in omnia_config_credential.yml file.
  And all nodes BMC credentials should be same.
  Rectify the issue and re-execute telemetry.yml.
unreachable_oim_bmc_msg: >
  The following BMC IPs are unreachable: {{ bmc_result.unreachable_bmc | join(', ') }}.
  Please provide BMC IPs which are reachable from OIM,
  else remove unreachable BMC entries from the {{ bmc_group_data_filename }} file.
unreachable_service_node_bmc_msg: >
  The following BMC IPs are unreachable: {{ bmc_result.unreachable_bmc | join(', ') }}.
  Please provide BMC IPs which are reachable from service node: {{ node_host }},
  else remove unreachable BMC entries from the {{ bmc_group_data_filename }} file.
invalid_bmc_warning_msg: |
  [WARNING] Some BMC IPs are not valid. Kindly address the issues mentioned above and execute telemetry.yml.
  Telemetry feature wont be enabled for these BMC IPs from {{ bmc_group_data_filename }} file.

# Usage: validate_bmcips_reachability.yml
idrac_telemetry_scripting_git_clone_path: "/opt/omnia/telemetry/idrac_telemetry/iDRAC-Telemetry-Scripting"

# Usage: trigger_telemetry_collection.yml
idrac_telemetry_container: "idrac_telemetry_receiver"
idrac_telemetry_receiver_entry_script: "/usr/local/bin/idrac_telemetry_receiver_init.sh"
idrac_telemetry_restart_failure_msg: |
  Failed to restart idrac_telemetry_receiver container. Please check the logs using the command `podman logs idrac_telemetry_receiver` and try again later.

idrac_telemetry_statefulset_restart_failure_msg: |
  Failed to restart the  {{ idrac_telemetry_k8s_name }} StatefulSet.
  Please check the logs using the command kubectl logs -n {{ telemetry_namespace }} {{ idrac_telemetry_k8s_name }}-<pod-index> and try again.

# Usage: create_telemetry_report.yml
telemetry_report_path: "/opt/omnia/telemetry/idrac_telemetry_report.yml"
telemetry_report_template: "telemetry_report.j2"
telemetry_report: |
      ---- Telemetry Report Overview ----

      IP count with Telemetry not supported: {{ failed_idrac_count | int + invalid_idrac_count | int }}
      IP count with Telemetry activated in current execution: {{ telemetry_idrac_count | int }}

      {% if (failed_idrac_count | int + invalid_idrac_count | int) > 0 %}
      Potential reasons for telemetry not being initiated include Redfish connectivity problems, timeout issues,
      iDRAC datacenter license constraints, or firmware-related problems.
      {% endif %}
      {% if idrac_redfish_disabled | length > 0 %}
      IPs with Redfish disabled:
      {% for item in idrac_redfish_disabled %}
        - {{ item }}
      {% endfor %}
      {% endif %}
      {% if idrac_invalid_creds | length > 0 %}
      IPs with invalid credentials:
      {% for item in idrac_invalid_creds %}
        - {{ item }}
      {% endfor %}
      {% endif %}
      {% if idrac_unreachable | length > 0 %}
      IPs with unreachable BMC:
      {% for item in idrac_unreachable %}
        - {{ item }}
      {% endfor %}
      {% endif %}
      {% if failed_idrac | length > 0 %}
      Telemetry not supported because of iDRAC Datacenter license constraints or firmware issues.
      IPs List:
      {% for item in failed_idrac %}
        - {{ item }}
      {% endfor %}
      {% endif %}
