# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

local_repo_access_config_file: "/opt/omnia/provision/local_repo_access.yml"
input_project_dir: "{{ hostvars['localhost']['input_project_dir'] }}"
k8s_packages_file: "{{ input_project_dir }}/config/x86_64/{{ software_config.cluster_os_type }}/{{ software_config.cluster_os_version }}/service_k8s.json" # noqa: yaml[line-length]
calico_manifest_yaml_url: "{{ offline_manifest_path }}/{{ calico_package }}/{{ calico_package }}.yml"
metallb_manifest_yaml_url: "{{ offline_manifest_path }}/{{ metallb_package }}/{{ metallb_package }}.yml"
multus_manifest_yaml_url: "{{ offline_manifest_path }}/{{ multus_package }}/{{ multus_package }}.yml"
helm_tarball_url: "{{ offline_tarball_path }}/{{ helm_package }}/{{ helm_package }}.tar.gz"
nfs_client_provisioner_tarball_url: "{{ offline_tarball_path }}/{{ nfs_subdir_external_provisioner_pkg }}/{{ nfs_subdir_external_provisioner_pkg }}.tar.gz"
whereabouts_git_url: "{{ offline_git_path }}/{{ whereabouts_pkg }}/{{ whereabouts_pkg }}.tar.gz"
file_mode: "0644"
ha_config_file: "{{ input_project_dir }}/high_availability_config.yml"
pulp_webserver_cert_path: "/opt/omnia/pulp/settings/certs/pulp_webserver.crt"
anchors_path: "/etc/pki/ca-trust/source/anchors/pulp_webserver.crt"

# Usage: create_node_dir.yml
nodes_yaml: "{{ hostvars['localhost']['oim_shared_path'] }}/omnia/openchami/workdir/nodes/nodes.yaml"
worker_components:
  - 'kubernetes'
  - 'kubelet'
  - 'pod-logs'
worker_ips: "{{ worker_ip_list | unique }}"
cp_components:
  - 'etcd'
  - 'kubernetes'
  - 'kubelet'
  - 'pod-logs'
k8s_pip_packages: []
cp_ips: "{{ (cp_first_ip_list + cp_ip_list) | unique }}"
folder_mode: "0755"

# csi variables
csi_powerscale_git: "csi-powerscale.tar.gz"
fail_msg_download: "Failed to get required dependencies. Make sure to verify entries in csi_driver_powerscale.json and run local_repo.yml first."
helm_charts_git: "helm-charts.tar.gz"
external_snapshotter_git: "external-snapshotter.tar.gz"
empty_certificate_template_path: "{{ role_path }}/files/empty_certificate_template.yml"
permission_644: "0644"
owner_value: "root"
group_value: "root"
csi_powerscale_secret_vaultname: ".csi_powerscale_secret_vault"
vault_key_permission: "0644"

# Usage ps_storage_class.j2
ps_isipath: "{{ csi_powerscale_values_file['isiPath'] }}"
ps_access_zone: "{{ csi_powerscale_values_file['isiAccessZone'] }}"
ps_azserviceip: "{{ clusters.isilonClusters[0].endpoint | regex_replace('https?://', '') | regex_replace('/.*', '') }}"

nfs_export_help_msg: |
  Failed to create required subdirectories at '{{ k8s_client_mount_path }}'.
  Please check that the NFS server ({{ k8s_nfs_server_ip }}) is exporting the directory with correct permissions.
  Example /etc/exports line on your NFS server:

    {{ k8s_server_share_path }} *(rw,sync,no_root_squash,no_subtree_check)

  After updating /etc/exports
  1) Run 'exportfs -ra' on the NFS server and verify permissions/mounts
  2) Execute 'systemctl restart nfs-server'
  3) Rerun the playbook.
