# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# ***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.
# SIMPLY APPEND THE REQUIRED VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
# ***********************************************************************

# -----------------------------SLURM------------------------------------------------
# slurm_cluster
# List of slurm clusters
# cluster_name is required field

# nfs_storage_name
# Storage name corresponding to the NFS share to be used by slurm cluster 
# This should match with exactly with a entry in storage_config.yml

# config_sources
# defines how the Slurm configuration files are provided to the cluster.
# <conf name>: 
#    <mapping>
# <mapping> Supply the configuration values directly as a keyâ€“value map
# The conf files supported by slurm are
# slurm
# cgroup
# gres
# mpi
# helpers
# job_container
# acct_gather
# oci
# plugstack
# topology
# Thes files will be written into the slurm_config directory with .conf suffix

slurm_cluster:
  - cluster_name: slurm_cluster
    nfs_storage_name: nfs_slurm
    # config_sources:
    #   slurm:
    #     SlurmctldTimeout: 60
    #     SlurmdTimeout: 150
    #   cgroup: 
    #     CgroupPlugin: autodetect
    #     AllowedRAMSpace: 100
  
# ----------------------------SERVICE K8S------------------------------------------------------
# For service k8s cluster below parameters are required,(List)
# - cluster_name is required field

# - deployment: Exactly one entry in both the service_k8s_cluster lists must have deployment set to true to indicate where Kubernetes should be deployed.
# Please ensure corresponding cluster entry is added to high_availability_config.yml if deployment is set to true. 

# - Kubernetes SDN network.K8s_cni (Mandatory) - It can either be "calico" or "flannel".Default value assigned is "calico".
# While setting up Kubernetes plugin for RoCE NIC, ensure that this value is set to "flannel"

# - pod_external_ip_range: (Mandatory) These addresses will be used by Loadbalancer for assigning External IPs to K8s services
# Make sure the IP range is not assigned to any node in the cluster.
# Acceptable formats: "10.11.0.100-10.11.0.150" , "10.11.0.0/16"

# - k8s_service_addresses: Kubernetes internal network for services.This network must be unused in your network infrastructure.
# Default value is "10.233.0.0/18"

# - k8s_pod_network_cidr: Kubernetes pod network CIDR for internal network. When used, it will assign IP addresses from this range to individual pods.
# This network must be unused in your network infrastructure.
# Default value is "10.233.64.0/18"

# nfs_storage_name : The nfs name should be same as one of the nfs name defined in storage_config.yml to configure the server.
# ----------------------------CSI Driver------------------------------------------------------
# Following csi powerscale driver input variables are mandatory only if csi_driver_powerscale entry is present in software_config.json
# csi_powerscale_driver_secret_file_path: Absolute file path for the secret.yaml file.
# User need to download secret.yaml file and fill required data in secret file. Provided the path of the secret file here.
# File path for the values.yml file which will contain the Powerscale driver configuration parameters.
# csi_powerscale_driver_values_file_path: User need to download values.yaml file and fill required data in values.yaml file. Provided the path of the values.yaml file here.
# mention configurable values

service_k8s_cluster:
  - cluster_name: service_cluster
    deployment: true
    k8s_cni: "calico"
    pod_external_ip_range: "172.16.107.170-172.16.107.200"
    k8s_service_addresses: "10.233.0.0/18"
    k8s_pod_network_cidr: "10.233.64.0/18"
    nfs_storage_name: "nfs_k8s"
    csi_powerscale_driver_secret_file_path: ""
    csi_powerscale_driver_values_file_path: ""
