# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Set kubespray service
  ansible.builtin.set_fact:
    kubespray_service_list: ""

- name: Set Kubespray service if not empty
  ansible.builtin.set_fact:
    kubespray_service_list: "{{ kubespray_versions | map('regex_replace', '^(.*)$', 'omnia_kubespray_\\1.service') | join(' ') }}"
  when: kubespray_versions is defined

- name: Initialize auth service variable
  ansible.builtin.set_fact:
    auth_service: ""

- name: Set auth service if openldap is present
  ansible.builtin.set_fact:
    auth_service: "omnia_auth.service"
  when: hostvars['localhost']['openldap_support']

- name: Start network manager services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items: "{{ network_services }}"

- name: Create omnia.target service
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ omnia_service_path }}"

- name: Start the omnia.target service
  ansible.builtin.systemd:
    name: omnia.target
    daemon_reload: true
    state: started
    enabled: true
