# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Show status of the Lifecycle Controller
  dellemc.openmanage.idrac_lifecycle_controller_status_info:
    idrac_ip: "{{ inventory_hostname }}"
    idrac_user: "{{ bmc_username | default(hostvars['localhost']['bmc_username']) }}"
    idrac_password: "{{ bmc_password | default(hostvars['localhost']['bmc_password']) }}"
    validate_certs: false
  register: lc_check_status

- name: Check LC availibility
  ansible.builtin.fail:
    msg: "{{ lc_check_fail_msg }}"
  when: not lc_check_status.lc_status_info.LCReady

- name: Set reboot type
  ansible.builtin.set_fact:
    reboot_type: "{{ 'none' if not restart_host else ('force_restart' if force_restart else 'graceful_restart') }}"

- name: Set boot from pxe
  dellemc.openmanage.idrac_boot:
    idrac_ip: "{{ inventory_hostname }}"
    idrac_user: "{{ bmc_username | default(hostvars['localhost']['bmc_username']) }}"
    idrac_password: "{{ bmc_password | default(hostvars['localhost']['bmc_password']) }}"
    validate_certs: false
    boot_source_override_mode: uefi
    boot_source_override_target: "{{ boot_source_override_target }}"
    boot_source_override_enabled: "{{ boot_source_override_enabled }}"
    reset_type: "{{ reboot_type }}"
  register: pxe_provisioning
  ignore_errors: true
  ignore_unreachable: true

- name: OS provisioning failed using PXE
  ansible.builtin.fail:
    msg: "{{ pxe_provisioning_fail_msg }}"
  when: pxe_provisioning is failed

- name: IDRAC might be unreachable during OS provisioning
  ansible.builtin.debug:
    msg: "{{ unreachable_idrac_msg }}"
  when: pxe_provisioning is unreachable

- name: Provision OS status
  ansible.builtin.debug:
    msg: "{{ provision_os_msg }}"
