# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Pre-requisites for service_cluster k8s
  when:
    - hostvars['localhost']['idrac_telemetry_support']
  block:
    - name: Include service_cluster metadata if already exists
      ansible.builtin.include_vars: "{{ service_cluster_metadata_path }}"
      delegate_to: localhost
      connection: local
      no_log: true
      failed_when: false

    - name: Fetch service_cluster info
      get_service_cluster_info:
        nodes_info: "{{ node_parsed_yaml.nodes }}"
        functional_groups_file_path: "{{ functional_groups_config_path }}"
        bmc_group_data: "{{ bmc_dict_list | default([]) }}"
      register: service_cluster_info_output
      delegate_to: localhost
      connection: local

    - name: Set fact for service_cluster role required and other facts
      ansible.builtin.set_fact:
        service_cluster_node_details: "{{ service_cluster_info_output.service_cluster_node_details | default({}) }}"

    - name: Create and update service node metadata file
      ansible.builtin.copy:
        dest: "{{ service_cluster_metadata_path }}"
        content: "{{ {'kube_client_share_path': service_cluster_idrac_telemetry_dir_path, 'kube_vip': kube_vip, 'service_cluster_metadata': service_cluster_node_details} | to_nice_yaml }}" # noqa: yaml[line-length]
        mode: "{{ metadata_perm }}"
        force: true
      delegate_to: localhost
      connection: local
      no_log: true
