# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---

metadata_file_path: "/opt/omnia/offline_repo/.data/localrepo_metadata.yml"
local_repo_check_msg: |
  Failure: metadata file is not present at path {{ metadata_file_path }}.
  Please make sure that local_repo.yml playbook is executed successfully.
input_project_dir: "{{ hostvars['localhost']['input_project_dir'] }}"
functional_groups_file_path: "{{ hostvars['localhost']['functional_groups_config_path'] }}"
software_config_file_path: "{{ input_project_dir }}/software_config.json"
aarch64_build_image_completion_msg: |
  The playbook build_image_aarch64.yml has been completed successfully.
  To boot x86_64 and aarch64 nodes execute discovery/discovery.yml playbook.
functional_group_absent_msg: |
  Failure: No aarch64 functional groups found in functional_group_config.yml input file.
  Please make sure aarch64 functional_group should be present in input file functional_group_config.yml
  to execute build_image_aarch64.yml successfully.
