# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Load software_config.json as software_config
  block:
    - name: Load software_config.json as software_config
      ansible.builtin.include_vars:
        file: "{{ software_config_file }}"
        name: software_config
      register: include_software_config
      no_log: true
  rescue:
    - name: Failed to load software_config.json as software_config
      ansible.builtin.fail:
        msg: "{{ software_config_syntax_fail_msg }} Error: {{ include_software_config.message }}"

- name: Set facts for cluster
  ansible.builtin.set_fact:
    cluster_os_type: "{{ software_config.cluster_os_type }}"
    cluster_os_version: "{{ software_config.cluster_os_version }}"

- name: Initialise variables
  ansible.builtin.set_fact:
    service_k8s_support: false

- name: Check if service k8s support is true
  ansible.builtin.set_fact:
    service_k8s_support: "{{ software_config.softwares | selectattr('name', 'equalto', 'service_k8s') | list | length > 0 }}"

- name: Initialise openldap support variables
  ansible.builtin.set_fact:
    openldap_support: false

- name: Check if openldap support is true
  ansible.builtin.set_fact:
    openldap_support: "{{ software_config.softwares | selectattr('name', 'equalto', 'openldap') | list | length > 0 }}"
