# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---


- name: Get the variables
  when: hostvars['localhost']['openldap_support']
  block:
    - name: Extract the domain name required by LDAP
      ansible.builtin.set_fact:
        ldap_search_base: "{{ (hostvars['localhost']['domain_name'].split('.') | map('regex_replace', '^', 'dc=') | list) | join(',') }}"

    - name: Set the server-ip required by LDAP
      ansible.builtin.set_fact:
        ldap_server_ip: "{{ hostvars['localhost']['Networks'][0]['admin_network']['primary_oim_admin_ip'] }}"

    - name: Set the ldap_connection_type required by LDAP
      ansible.builtin.set_fact:
        connection_type: "{{ (hostvars['localhost']['ldap_connection_type']) | lower }}"

    - name: Set the password required by LDAP
      ansible.builtin.set_fact:
        password: "{{ hostvars['localhost']['openldap_db_password'] }}"
      no_log: true

    - name: Set the ldap_connection_type required by LDAP
      ansible.builtin.set_fact:
        ldap_default_bind_dn: "cn={{ hostvars['localhost']['openldap_db_username'] }},{{ ldap_search_base }}"

  rescue:
    - name: Warn missing vars files
      ansible.builtin.fail:
        msg: "{{ openldap_fail_msg }}"
