---
# vars/main.yml

# K8s functional groups (x86_64 example; extend if you have aarch64 variants)
k8s_functional_groups:
  - service_kube_control_plane_first_x86_64
  - service_kube_control_plane_x86_64
  - service_kube_node_x86_64

# Slurm / login functional groups
slurm_functional_groups:
  - slurm_control_node_x86_64
  - slurm_node_x86_64
  - login_node_x86_64
  - login_compiler_node_x86_64