# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Configure the ochami
  environment: "{{ hostvars['oim']['ochami_env'] }}"
  block:
    - name: Create groups
      ansible.builtin.include_tasks: create_groups.yml
      with_items: "{{ hostvars['localhost']['functional_groups'] | map(attribute='name') | list }}"

    - name: Fecth image of additional_packages.json file
      ansible.builtin.include_tasks: fetch_additional_images.yml

    - name: Create groups common
      ansible.builtin.include_tasks: create_groups_common.yml
      loop: "{{ common_cloud_init_groups }}"

    - name: Configure bss and cloud-init
      ansible.builtin.include_tasks: configure_bss_cloud_init.yml

    - name: Discovery completion
      ansible.builtin.include_tasks: discovery_completion.yml
