# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Remove from known_hosts
  ansible.builtin.known_hosts:
    name: "{{ hostvars[item]['ansible_fqdn'] }}"
    state: absent
  delegate_to: localhost
  run_once: true
  loop: "{{ ansible_play_hosts | default([]) }}"

- name: Remove from known_hosts
  ansible.builtin.known_hosts:
    name: "{{ hostvars[item]['ansible_fqdn'] | split('.') | first }}"
    state: absent
  delegate_to: localhost
  run_once: true
  loop: "{{ ansible_play_hosts | default([]) }}"

- name: Set hosts dict
  ansible.builtin.set_fact:
    hosts_dict: "{{ hosts_dict | default({}) |
     combine({item: (hostvars[item]['ansible_default_ipv4']['address'] |
     default(hostvars[item]['ansible_all_ipv4_addresses'][0]) | default(hostvars[item]['inventory_hostname']))
     + ' ' + hostvars[item]['ansible_fqdn'] + ' ' + hostvars[item]['ansible_fqdn'] | split('.') | first}) }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ ansible_play_hosts | default([]) }}"

- name: Add hosts file entry for cluster
  ansible.builtin.shell: |
    if ! grep -qxF '{{ item }}' {{ hosts_file_path }}; then
    echo '{{ item }}' >> {{ hosts_file_path }}
    fi
  delegate_to: localhost
  register: addhosts
  changed_when: addhosts.rc == 0
  failed_when: false
  run_once: true
  loop: "{{ hosts_dict.values() | default([]) }}"

- name: Update hosts file for all
  block:
    - name: Update hosts file
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ item }}"
        state: present
        create: true
        mode: "{{ hosts_file_mode }}"
      loop: "{{ hosts_dict.values() | default([]) }}"
  rescue:
    - name: Updating hosts file failed
      ansible.builtin.fail:
        msg: "{{ hosts_update_fail_msg }}"

- name: Read inputs
  ansible.builtin.include_tasks: read_inp.yml
  # run_once: true

- name: Create repo base on os_type
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Update pulp crt
  ansible.builtin.include_tasks: update_pulp_crt.yml
