# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
arch_antonyms:
  x86_64: aarch64
  aarch64: x86_64
hosts_file_dest: "/etc/hosts"
hosts_file_mode: "0644"
hosts_update_fail_msg: "Failed to update hosts file with node details.
 Remove unreachable IP addresses from slurm_node or login_node group of inventory and re-run the playbook."
hosts_file_path: /opt/omnia/hosts
repo_path: "/etc/yum.repos.d"
versioned_softwares:
  - beegfs
  - amdgpu
  - rocm

pulp_ssl_ca_cert: "/etc/pki/ca-trust/source/anchors/pulp_webserver.crt"
local_repo_keys_x86_64:
  - user_repo_url_x86_64
  - rhel_os_url_x86_64
  - omnia_repo_url_rhel_x86_64
local_repo_keys_aarch64:
  - user_repo_url_aarch64
  - rhel_os_url_aarch64
  - omnia_repo_url_rhel_aarch64

software_version_default: "omnia_default"
file_permission: "0644"

input_project_dir: "{{ hostvars['localhost']['input_project_dir'] }}"
software_config_json_file: "{{ input_project_dir }}/software_config.json"
local_repo_config_file: "{{ input_project_dir }}/local_repo_config.yml"

# Usage:validate_repo.yml
pulp_bin_path: /usr/local/bin/pulp
repo_fail_msg: "Failed. Please execute local_repo.yml to create pulp repositories"
repo_retries: 5
repo_delay: 10
repo_update_failure_msg: "The playbook failed due to an error while running dnf makecache.
     Please check if repos configured in local_repo_config.yml and ensure they are correct and reachable"

# Usage: update_pulp_crt.yml
pulp_cert_src: "/opt/omnia/pulp/settings/certs/pulp_webserver.crt"
ca_trust_path: "/etc/pki/ca-trust/source/anchors/"
