# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Initialize list of tags
  ansible.builtin.set_fact:
    omnia_run_tags: "{{ ansible_run_tags | default([]) }}"
  when: omnia_run_tags is not defined

- name: Check if functional_groups_config.yml exists
  ansible.builtin.stat:
    path: "{{ functional_groups_config_path }}"
  register: functional_groups_config_stat

- name: Generate functional groups configuration if not present
  when: not functional_groups_config_stat.stat.exists
  block:
    - name: Include vars from provision_config.yml
      ansible.builtin.include_vars:
        file: "{{ input_project_dir }}/provision_config.yml"

    - name: Generate functional groups from mapping.csv
      generate_functional_groups:
        mapping_file_path: "{{ pxe_mapping_file_path }}"
        functional_groups_file_path: "{{ functional_groups_config_path }}"
        omnia_config_path: "{{ input_project_dir }}/omnia_config.yml"

    - name: Verify functional_groups_config.yml was created
      ansible.builtin.stat:
        path: "{{ functional_groups_config_path }}"
      register: functional_groups_file_check

    - name: Fail if functional groups file was not created
      ansible.builtin.fail:
        msg: "{{ messages.functional_groups_generation_fail }}"
      when: not functional_groups_file_check.stat.exists
      
- name: Validate omnia input config
  vars:
    # Note: When running a specific playbook without tags ansible run tags will default to ["all"], thus if two or more tags are present
    # then the "all" tag should be removed so that only the config files related to that playbook are validated.
    input_validate_tags: "{{ omnia_run_tags | default([]) | difference(['all']) if (omnia_run_tags | length) >= 2
      else omnia_run_tags | default([]) }}"
  validate_input:
    omnia_base_dir: "{{ (input_dir + '/../') | ansible.builtin.realpath }}"
    project_name: "{{ project_name }}"
    tag_names: "{{ input_validate_tags }}"
    module_utils_path: "{{ (role_path + '/../../../common/library/module_utils/') | ansible.builtin.realpath }}"
  register: validation_status
  when: (input_validate_tags | length) > 0

- name: Debug validation status
  ansible.builtin.debug:
    msg: "{{ messages.validation_success }}"
