# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Pre-requisites for service_cluster k8s
  when:
    - hostvars['localhost']['idrac_telemetry_support']
    - hostvars['localhost']['federated_idrac_telemetry_collection']
  block:
    - name: Include roles_config.yml
      block:
        - name: Include roles_config.yml
          ansible.builtin.include_vars: "{{ roles_config_path }}"
          register: include_roles_config
          tags: init
      rescue:
        - name: Failed to include  roles_config.yml
          ansible.builtin.fail:
            msg: "{{ roles_config_syntax_fail_msg }} Error: {{ include_roles_config.message }}"

    - name: Determine layer
      ansible.builtin.set_fact:
        layer: "default"

    - name: Fetch composable roles data
      fetch_roles_config:
        roles_data: "{{ Roles }}"
        groups_data: "{{ Groups }}"
        layer: "{{ layer }}"
      register: composable_roles_output

    - name: Set Facts for composable roles data
      ansible.builtin.set_fact:
        groups_info: "{{ composable_roles_output.groups_roles_info }}"

    - name: Include service_cluster metadata if already exists
      ansible.builtin.include_vars: "{{ service_cluster_metadata_path }}"
      no_log: true
      failed_when: false

    - name: Build host_inventory list # noqa: jinja[invalid]
      ansible.builtin.set_fact:
        host_inventory: >-
          {{
            (
              (
                (groups['kube_control_plane'] | default([]))
                + (groups['etcd'] | default([]))
                + (groups['kube_node'] | default([]))
              )
              +
              (
                (
                  (groups['kube_control_plane'] | default([]))
                  + (groups['etcd'] | default([]))
                  + (groups['kube_node'] | default([]))
                )
                | map('extract', hostvars)
                | selectattr('ansible_host', 'defined')
                | map(attribute='ansible_host')
                | list
              )
            ) | unique
          }}

    - name: Fetch service_cluster info
      get_service_cluster_info:
        groups_info: "{{ groups_info }}"
        host_inventory: "{{ host_inventory }}"
      register: service_cluster_info_output

    - name: Set fact for service_cluster role required and other facts
      ansible.builtin.set_fact:
        service_cluster_node_details: "{{ service_cluster_info_output.service_cluster_node_details | default({}) }}"

    - name: Merge existing and new service node details
      ansible.builtin.set_fact:
        service_cluster_metadata: >-
          {{
            service_cluster_node_details | combine(service_cluster_metadata | default({}), recursive=True)
          }}

    - name: Create and update service node metadata file
      ansible.builtin.copy:
        dest: "{{ service_cluster_metadata_path }}"
        content: "{{ {'service_cluster_metadata': service_cluster_metadata} | to_nice_yaml }}"
        mode: "{{ metadata_perm }}"
        force: true
